#!/bin/bash

set -exuo pipefail

PROJDIR="$(pwd)"

pushd "$(pwd)"
trap popd EXIT

if [[ -f "$BUILDKITE_PLUGIN_CODECOV_PATH" ]]; then
    echo "--- Uploading $BUILDKITE_PLUGIN_CODECOV_PATH to Codecov"

    DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
    cd $DIR/../

    ./codecov -X gcov -X search -f "$PROJDIR/$BUILDKITE_PLUGIN_CODECOV_PATH" -B $BUILDKITE_BRANCH -C $BUILDKITE_COMMIT -P $BUILDKITE_PULL_REQUEST -b $BUILDKITE_BUILD_NUMBER
else
    echo "--- Coverage report at $BUILDKITE_PLUGIN_CODECOV_PATH was not found, skipping"
fi
